## Loader Properties
modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Zhincore/xaero-train-map-1-20"
#logoFile="examplemod.png" #optional
issueTrackerURL = "https://github.com/Zhincore/xaero-train-map-1-20/issues"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "xaeroworldmap"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "create"
mandatory = true
versionRange = "[6.0.0,)"
ordering = "NONE"
side = "CLIENT"
